pg_authid is not avaialble on aws rds postgres
ansible-collections/community.postgresql pull request #171
Opened 2021-12-14 21:27 UTC by marcosdiez

closes #170
closes #169

2021-12-14 22:05 UTC, tcraxs requested changes

2021-12-14 22:05 UTC, tcraxs commented on plugins/modules/postgresql_info.py
> +                 "FROM pg_catalog.pg_namespace AS n ")
> missing FROM-clause entry for table "a"

`a.oid` is not possible here

> [testhost] testhost: postgresql_info : postgresql_info - test return values and session_role param login_user={{ pg_user }}, login_db={{ db_default }}, login_port={{ replica_port }}, session_role=session_superuser
> Cannot execute SQL 'SELECT n.nspname, pg_catalog.pg_get_userbyid(a.oid) AS rolname, n.nspacl FROM pg_catalog.pg_namespace AS n ': missing FROM-clause entry for table "a" LINE 1: SELECT n.nspname, pg_catalog.pg_get_userbyid(a.oid) AS rolna...                                                      ^

2021-12-14 22:11 UTC, marcosdiez commented on plugins/modules/postgresql_info.py
> +                 "FROM pg_catalog.pg_namespace AS n ")
my bad. fixed!

2021-12-15 11:49 UTC, tcraxs commented
@marcosdiez Thanks for fixing the CI problem.
Could you also add a changelog fragment for this PR: https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment

Could you also check if integration tests are needed for this change. See the content of tests/integration/target/postgresql_info/tasks

2021-12-15 12:00 UTC, marcosdiez commented
Hi @tcraxs 

This PR specifically does not need unit tests (or the exiting ones suffice)
I just added the  changelog fragment file.

now, somehow my tests are failing and I don't know why.
please help me

2021-12-15 13:26 UTC, MichaelDBA approved these changes
I was able to validate all the sql changes in this python module.

2021-12-20 07:10 UTC, Andersson007 commented
closed reopened to relaunch CI

2021-12-20 07:31 UTC, Andersson007 approved these changes
LGTM

2021-12-20 07:31 UTC, merged

2021-12-20 07:33 UTC, Andersson007 commented
@marcosdiez thank you for the contribution! (CI errors weren't related to you fix). Great job!
@tcraxs @MichaelDBA thank you for reviewing and testing!