fix reconnect()
ansible-collections/community.postgresql pull request #173
Opened 2021-12-15 01:49 UTC by marcosdiez

##### SUMMARY
fixes #172

The reason `postgres_info.py` was gathering data on every database was because of a bug in `PgDbConn.reconnect()`, which is fixed here.

I also changed the main loop that iterate among all DBs to ignore DBs which it can't access because in AWS RDS not all DBs are accessible.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
postgres_info.py

2021-12-15 05:57 UTC, Andersson007 commented
@marcosdiez hi and welcome to the project! Thank you for the bunch of issues and fixes! Could you please:
- Make CI green
- Add a changelog fragment to each PRs https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment
- Add integration tests (where possible). See the content of `tests/integration/target/postgresql_info/tasks`

2021-12-20 07:07 UTC, Andersson007 commented
@marcosdiez thank you for the PR, could you please:
1. Fix CI, everything should be green (see the "Details" link for details)
2. Be sure the changes is covered with integration tests, see the content of `tests/integration/targets/postgresql_info/tasks`

2021-12-20 07:11 UTC, Andersson007 commented
closed reopened to re-trigger CI

2021-12-20 07:25 UTC, Andersson007 commented
@marcosdiez ah, the failings are unrelated (there are AZP issues there), sorry
So please cover the case mentioned in https://github.com/ansible-collections/community.postgresql/issues/172 somewhere within `tests/integration/targets/postgresql_info/tasks` and let us know when it's ready for review

2021-12-20 07:27 UTC, Andersson007 requested changes

2021-12-20 07:27 UTC, Andersson007 commented on changelogs/fragments/173-postgres_info_now_shows_the_info_of_each_specific_database.yml
> +- postgres_info - Specific info (namespaces, extensions, languages) of each database was not being shown properly. Instead, the info from the DB that was connected was always being shown.
```suggestion
- postgres_info - Specific info (namespaces, extensions, languages) of each database was not being shown properly. Instead, the info from the DB that was connected was always being shown (https://github.com/ansible-collections/community.postgresql/issues/172).
```

2021-12-20 07:27 UTC, Andersson007 commented on plugins/modules/postgresql_info.py
> +                db_dict[datname]['error'] = "could not connect to the database (probably permission issue)"
```suggestion
                db_dict[datname]['error'] = "Could not connect to the database."
```
I suggest avoiding assumptions. Later we could think how to return actual errors.

2021-12-26 23:03 UTC, marcosdiez commented
@Andersson007 hi! Unit tests added. Sorry for the delay, but it took me longer to find out how to run unit tests locally then to actually write them.

By the way, the solution I found is `time ansible-test integration --target docker:ubuntu2004 --docker-terminate never -v postgresql_info` which is taking a little more than a minute on each iteration.

I still have not found a way to use the same container and hence not  have to download postgres every time I want to run unit tests.

Please feel free to core review this PR and request changes as needed.
Thanks!

2022-01-03 11:21 UTC, Andersson007 approved these changes
LGTM

2022-01-03 11:21 UTC, merged

2022-01-03 11:22 UTC, Andersson007 commented
@marcosdiez thanks for the great contribution!:)

2022-01-03 11:26 UTC, Andersson007 commented
> By the way, the solution I found is time ansible-test integration --target docker:ubuntu2004 --docker-terminate never -v postgresql_info which is taking a little more than a minute on each iteration.

I just use `ansible-test integration postgresql_info --docker ubuntu2004 -vvv > ~/test.log`, never dug into it deeply. I'll compare your command with this simplest one next time, thank you!