postgresql_ping: improve documentation
ansible-collections/community.postgresql pull request #176
Opened 2021-12-17 10:44 UTC by Andersson007

##### SUMMARY
Relates to https://github.com/ansible-collections/community.postgresql/issues/174

##### ISSUE TYPE
- Docs Pull Request

2021-12-17 14:25 UTC, hunleyd requested changes

2021-12-17 14:25 UTC, hunleyd commented on plugins/modules/postgresql_ping.py
> +    register return values into the result variable for future use
```suggestion
    Ping PostgreSQL server using non-default credentials and SSL
    registering the return values into the result variable for future use
```

2021-12-17 14:25 UTC, hunleyd commented on plugins/modules/postgresql_ping.py
> +# You can use the variable with another task
```suggestion
# You can use the registered result with another task
```

2021-12-20 06:06 UTC, Andersson007 commented
@hunleyd , committed the suggestions, now the comments are much better! thanks!:)

2021-12-20 12:53 UTC, Andersson007 commented
PTAL

2021-12-20 13:12 UTC, hunleyd approved these changes

2022-01-03 11:26 UTC, merged

2022-01-03 11:26 UTC, Andersson007 commented
@hunleyd thanks for reviewing!