Release 1.7.5 commit
ansible-collections/community.postgresql pull request #319
Opened 2022-07-26 14:11 UTC by betanummeric

## release version 1.7.5

I ommited the changelog fragment `changelogs/fragments/0-postgresql_user-deprecate-privs-manipulation.yml`.

2022-07-26 15:48 UTC, hunleyd approved these changes

2022-07-27 05:49 UTC, Andersson007 approved these changes

2022-07-27 05:52 UTC, Andersson007 requested changes
@betanummeric could you please add `hangelogs/fragments/0-postgresql_user-deprecate-privs-manipulation.yml` as its purpose is to notify users about the future change?

Sorry, I wasn't clear, when saying "ignore" i meant ignore it when calculating the release version number.
The rest LGTM

2022-07-27 11:14 UTC, Andersson007 approved these changes

2022-07-27 11:14 UTC, merged