Release 2.2.0 commit
ansible-collections/community.postgresql pull request #320
Opened 2022-07-26 14:19 UTC by betanummeric

## release version 2.2.0
I ommited the changelog fragment `changelogs/fragments/0-postgresql_user-deprecate-privs-manipulation.yml`.

to be merged *after* https://github.com/ansible-collections/community.postgresql/pull/319

2022-07-26 16:12 UTC, hunleyd approved these changes

2022-07-27 05:51 UTC, Andersson007 commented
@betanummeric could you please add `hangelogs/fragments/0-postgresql_user-deprecate-privs-manipulation.yml` as its purpose is to notify users about the future change?

2022-07-27 05:51 UTC, Andersson007 requested changes
@betanummeric could you please add `hangelogs/fragments/0-postgresql_user-deprecate-privs-manipulation.yml` as its purpose is to notify users about the future change?

2022-07-27 11:15 UTC, Andersson007 approved these changes

2022-07-27 11:15 UTC, merged