[WIP] Added two new parameters ssl_cert and ssl_key
ansible-collections/community.postgresql pull request #427
Opened 2023-03-08 18:36 UTC by aleksvagachev

##### SUMMARY
Added two new parameters ssl_cert and ssl_key to solve the issue: #424
Added an integration test to check the ssl connection

##### ISSUE TYPE
- Feature Pull Request

2023-03-13 12:37 UTC, hunleyd requested changes
Could you please add the fragment using docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment, so that our users will know about the fix

2023-03-14 17:17 UTC, aleksvagachev commented
@hunleyd @Andersson007 Added changelog and integration test, do I need to add anything else?

2023-03-15 17:08 UTC, hunleyd approved these changes

2023-03-15 17:10 UTC, hunleyd commented
@aleksvagachev lgtm .. @Andersson007 is on PTO this week, iirc but he'll look at it once he's back. i'd like another approval before i merge it (just to be safe)

2023-03-20 12:22 UTC, Andersson007 commented
@aleksvagachev if it's ready for review, could you please remove WIP from the title?

2023-03-20 12:26 UTC, Andersson007 reviewed
@aleksvagachev looks just great, thanks very much!

A couple of minor things from me

2023-03-20 12:26 UTC, Andersson007 commented on changelogs/fragments/1-postgres.yml
> +- postgresql - added new parameters ssl_cert and ssl_key for ssl connection (https://github.com/ansible-collections/community.postgresql/issues/424).
```suggestion
- postgresql - added new parameters ``ssl_cert`` and ``ssl_key`` for ssl connection (https://github.com/ansible-collections/community.postgresql/issues/424).
```
to highlight them in rst a bit

2023-03-20 12:26 UTC, Andersson007 commented on plugins/doc_fragments/postgres.py
> +    type: path
```suggestion
    type: path
    version_added: '2.4.0'
```

2023-03-20 12:26 UTC, Andersson007 commented on plugins/doc_fragments/postgres.py
> +    type: path
```suggestion
    type: path
    version_added: '2.4.0'
```

2023-03-21 07:06 UTC, Andersson007 approved these changes
LGTM, thanks!

2023-03-21 12:14 UTC, merged