Added checking of available columns when receiving a subscription from the database
ansible-collections/community.postgresql pull request #437
Opened 2023-03-27 18:08 UTC by aleksvagachev

##### SUMMARY
When an unprivileged user received a subscription, an error occurred: permission denied for table pg_subscription.
Now a check has been added, by getting the available columns and displaying only them.
Solution of the issue: #429 

##### ISSUE TYPE
Feature Pull Request

2023-03-27 18:18 UTC, hunleyd approved these changes

2023-03-27 18:19 UTC, hunleyd requested changes
code _looks_ ok, but pls fix the failing tests

2023-03-29 13:05 UTC, jchancojr requested changes
lgtm pending @hunleyd suggestions

2023-03-29 13:34 UTC, Andersson007 approved these changes
brilliant, thanks!

2023-03-30 18:54 UTC, hunleyd approved these changes

2023-03-30 18:54 UTC, merged

2023-03-31 10:54 UTC, Andersson007 commented
thanks everyone for the contribution!