Psycopg and server version
ansible-collections/community.postgresql pull request #518
Opened 2023-07-03 12:55 UTC by elpavel

##### SUMMARY
Psycopg version 2 and 3 provide the database server version slightly differently.

This PR takes advantage of existing get_server_version function which already handles the Psycopg functionality change.
It will help with https://github.com/ansible-collections/community.postgresql/issues/499.

No functionality change

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
Several modules

##### ADDITIONAL INFORMATION

2023-07-05 14:04 UTC, hunleyd requested changes
pls add a changelog [fragment](https://github.com/ansible-community/antsibull-changelog/blob/main/docs/changelogs.rst#id15)

2023-07-06 08:14 UTC, elpavel commented
> pls add a changelog [fragment](https://github.com/ansible-community/antsibull-changelog/blob/main/docs/changelogs.rst#id15)

OK, fragment added

2023-07-06 14:02 UTC, hunleyd approved these changes

2023-07-10 09:31 UTC, Andersson007 approved these changes

2023-07-10 09:31 UTC, merged

2023-07-10 09:32 UTC, Andersson007 commented
@elpavel thanks for the contribution! @hunleyd thanks for reviewing!