Psycopg refactor and Fedora 38 test fix
ansible-collections/community.postgresql pull request #540
Opened 2023-07-17 21:52 UTC by elpavel

##### SUMMARY
Fixed the Fedora 38 test build.
Plus more psycopg related refactoring to help with #499

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
* postgresql_user_obj_stat_info
* Fedora 38 tests

##### ADDITIONAL INFORMATION
The `exec_sql` function in postgresql_user_obj_stat_info doesn't work when psycopg3 is used, passing an undefined parameter.
It has been fixed by only passing the parameter when it is needed.

2023-07-18 08:28 UTC, Andersson007 approved these changes

2023-07-18 12:34 UTC, hunleyd requested changes
missing changelog fragment for the query parameter part of this?

2023-07-18 12:39 UTC, Andersson007 commented
@hunleyd do you think if it touches user's side? We usually don't cover refactoring PRs

2023-07-19 12:18 UTC, hunleyd commented
> @hunleyd do you think if it touches user's side? We usually don't cover refactoring PRs

oh, the description said 'feature', lol

2023-07-19 14:51 UTC, merged

2023-07-20 07:39 UTC, Andersson007 commented
thanks the persistent work on this epic:)