Deprecate postgresql_lang
ansible-collections/community.postgresql pull request #559
Opened 2023-08-09 13:32 UTC by elpavel

##### SUMMARY
Deprecating the postgresql_lang module.

The lang module works only on old Postgresql versions.

The [documentation](https://www.postgresql.org/docs/12/sql-createlanguage.html) says
_As of PostgreSQL 9.1, most procedural languages have been made into “extensions”, and should therefore be installed with CREATE EXTENSION not CREATE LANGUAGE._

##### ISSUE TYPE
- Module Deprecation Pull Request

##### COMPONENT NAME
postgresql_lang

##### ADDITIONAL INFORMATION

Fixes #519

2023-08-09 17:13 UTC, jchancojr approved these changes

2023-08-10 07:57 UTC, Andersson007 requested changes
@elpavel thanks for starting the process!

I think we should follow the [official deprecation guide](https://docs.ansible.com/ansible/latest/dev_guide/module_lifecycle.html#deprecating-modules-and-plugins-in-a-collection), could you please take a look?

Apologies for not mentioning this before

2023-08-10 10:19 UTC, Andersson007 reviewed
LGTM

one more small formatting things

2023-08-10 10:19 UTC, Andersson007 commented on plugins/modules/postgresql_lang.py
> +- alternative: Use M(postgresql_ext) instead.
```suggestion
- alternative: Use M(community.postgresql.postgresql_ext) instead.
```
Using a FQCN is a [requirement](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#linking-and-other-format-macros-within-module-documentation) with this type of macros

2023-08-10 11:44 UTC, Andersson007 requested changes

2023-08-10 11:44 UTC, Andersson007 commented on plugins/modules/postgresql_lang.py
> +
```suggestion
```
i think we can remove it from here

2023-08-10 11:51 UTC, Andersson007 commented
@elpavel hm, it's strange, i see deprecations made same way in c.general, for example.. i'll ask the community

2023-08-10 12:05 UTC, Andersson007 commented
@elpavel just remove the hyphens, i didn't notice them.. thanks @felixfontein !

2023-08-10 13:13 UTC, Andersson007 approved these changes
LGTM

2023-08-11 10:58 UTC, Andersson007 approved these changes

2023-08-11 10:58 UTC, merged