Add pre-commit configuration
ansible-collections/community.postgresql pull request #583
Opened 2023-09-18 16:03 UTC by l00ptr

##### SUMMARY
Add some `pre-commit` configuration to enforce usage of linter, `autoflake`, `flake8` and `codespell` .

2023-09-19 14:56 UTC, hunleyd approved these changes
THANK YOU!!

2023-09-19 14:57 UTC, hunleyd requested changes
can you fix the conflicts pls? thx!

2023-09-20 09:17 UTC, l00ptr commented
Conflicts fixed! I can (probably tomorrow or friday) try to solve the (non-related) CI issue, do i need to create an issue for that ?

2023-09-20 12:12 UTC, hunleyd commented
> Conflicts fixed! I can (probably tomorrow or friday) try to solve the (non-related) CI issue, do i need to create an issue for that ?

no. you can solve it herein or just open a PR w/o issue

2023-09-25 12:35 UTC, hunleyd commented
#588 should resolve the CI issues, I believe

2023-09-27 13:59 UTC, hunleyd approved these changes

2023-09-27 13:59 UTC, merged

2023-10-02 05:28 UTC, Andersson007 commented
@l00ptr thanks for the contribution!
@hunleyd thanks for reviewing!

@l00ptr would you like to [backport](https://docs.ansible.com/ansible/devel/community/development_process.html#backporting-merged-prs-in-ansible-core) the changes manually to `stable-1` and `stable-2` (as there are conflicts) ?

2023-10-24 07:48 UTC, Andersson007 commented
@l00ptr we now get spelling errors in CI like:
![Screenshot from 2023-10-24 09-42-43](https://github.com/ansible-collections/community.postgresql/assets/34477873/6ed83d65-3c97-4def-a8c7-568f5d6fc56c)

can it relate to this PR? if yes, can we disable this?

2023-11-07 23:04 UTC, l00ptr commented
@Andersson007 do we still have a problem in CI with codespell ? The CI seems all green on master with codespell enabled.

2023-11-08 08:21 UTC, Andersson007 commented
@l00ptr now it's fine now in `main`. could you please check if the changes you made were backported as mentioned in the linked issue? if not, please [backport](https://docs.ansible.com/ansible/devel/community/development_process.html#backporting-merged-prs-in-ansible-core) them manually to `stable-2` and `stable-1` avoid merge conflicts in unrelated PRs.