Decode bytes object from sql_ascii databases
ansible-collections/community.postgresql pull request #585
Opened 2023-09-18 20:43 UTC by CalebDW

##### SUMMARY
Hello!

This PR fixes #584, however, I'm not sure if it's the only code that interacts with potentially encoded bytes.

Some other options are to:
- Do something like https://github.com/psycopg/psycopg/commit/ca6db5c213ad61af1f4690339248a3a447b31ef5
    - https://github.com/psycopg/psycopg/issues/503
    - https://github.com/psycopg/psycopg/issues/561
- Set a default connection parameter `client_encoding: utf8` in `postgres_common_argument_spec`

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`postgres_user`

##### ADDITIONAL INFORMATION

```paste below
```

2023-09-19 14:59 UTC, hunleyd requested changes
this looks ok to me, but i think we might want to:
> Set a default connection parameter client_encoding: utf8 in postgres_common_argument_spec

as you suggested. therefore, deferring until @Andersson007 returns from pto

2023-09-25 09:15 UTC, Andersson007 commented
@CalebDW hello, thanks for the fix!
Could you please:
- add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment)?
- can we add integration tests? i.e. create an encoded db and test everything works, the tests are located under the `tests/integration/targets` directory; how to run them is explained in the [quick start guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html)

2023-09-25 14:41 UTC, CalebDW commented
@Andersson007, sure I can do that. Do we still want to implement the changes requested by @hunleyd?

2023-09-25 21:44 UTC, CalebDW commented
@Andersson007, tests and changelog fragment have been added. Let me know if you want to keep the fix as-is or try to solve on a more global level

2023-09-26 07:07 UTC, Andersson007 commented
> @Andersson007, sure I can do that. Do we still want to implement the changes requested by @hunleyd?

Folks, i don't know what to say really:) I can judge the code and general things like testing but i've no idea what would work best from the users' perspective. I would follow "keep it simple" and avoid any risky changes if there are more straightforward solutions.
@hunleyd if you're not sure, please engage other maintainers / contributors calling for help in Matrix / pinging them here.

maybe @betanummeric and @aleksvagachev has ideas

2023-09-26 15:46 UTC, aleksvagachev commented
@CalebDW @Andersson007 @hunleyd I agree with the idea of "keep it simple". For specific parameters, you can use the "connect_params" field. We can try to leave it as it is for now, and if there are more issues related to this problem in the future, then we can add a parameter.

2023-09-27 14:01 UTC, hunleyd approved these changes

2023-10-02 12:05 UTC, Andersson007 commented
so as far as I can see people are ok to hold this on, right?
should we close the PR and the issue then?

2023-10-02 12:10 UTC, hunleyd commented
> so as far as I can see people are ok to hold this on, right? should we close the PR and the issue then?

i _think_ people were ok w/ this targeted fix and wanted to hold on the question of the larger sweeping change.

2023-10-03 08:56 UTC, Andersson007 approved these changes

2023-10-03 08:57 UTC, Andersson007 commented
oh, apologies folks, working in the text-scanning mode these days..
@hunleyd thanks for clarifying!:)
approved, thanks a lot! Please merge.

2023-10-03 12:10 UTC, merged

2023-10-04 07:48 UTC, Andersson007 commented
@CalebDW could you please backport the change to stable-2 and stable-1 manually https://docs.ansible.com/ansible/devel/community/development_process.html#backporting-merged-prs-in-ansible-core ?

If you have no time, please let me know

2023-10-04 12:58 UTC, CalebDW commented
@Andersson007, done, let me know if you need anything else!

2023-10-04 13:33 UTC, Andersson007 commented
> @Andersson007, done, let me know if you need anything else!

LGTM, merged, thanks!