Add support for icu_locale and locale_provider postgresql_db module.
ansible-collections/community.postgresql pull request #667
Opened 2024-02-02 14:35 UTC by aleszeleny

##### SUMMARY

Add support for **icu_locale** and **locale_provider** to **postgresql_db module**

##### ISSUE TYPE

- Feature Pull Request - [https://github.com/ansible-collections/community.postgresql/issues/666](issue 666)

##### COMPONENT NAME

**postgresl_db**

##### ADDITIONAL INFORMATION

Hopefully, the pull request will be usable to show the missing feature.

2024-02-02 16:49 UTC, aleszeleny commented
> seems reasonable. just needs a changelog fragment please @aleszeleny

Hello. I'm sorry, would you like me to post the description here as a comment or add the "v3.3.1" description into `CHANGELOG.rst` ?
Thanks

2024-02-07 15:35 UTC, hunleyd requested changes

2024-02-07 15:35 UTC, hunleyd commented on CHANGELOG.rst
Sorry, that's my bad. I meant to have you add a [changelog fragment](https://github.com/ansible-community/antsibull-changelog/blob/main/docs/changelogs.rst#examples). We should not edit CHANGELOG.rst directly, as we use antsibull-changelog to manage that file.

2024-02-07 18:43 UTC, aleszeleny commented
Hello,

that's fine, I'll remove it. Can I find somewhere a guide, whether it shall
be a new file (content format rules, a defined file name), or just post it
into GitHub conversation?

Thanks

Aleš Zelený

Aleš Zelený

Dne st 7. 2. 2024 16:35 uživatel Douglas J Hunley ***@***.***>
napsal:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On CHANGELOG.rst
> <https://github.com/ansible-collections/community.postgresql/pull/667#discussion_r1481670949>
> :
>
> Sorry, that's my bad. I meant to have you add a changelog fragment
> <https://github.com/ansible-community/antsibull-changelog/blob/main/docs/changelogs.rst#examples>.
> We should not edit CHANGELOG.rst directly, as we use antsibull-changelog to
> manage that file.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ansible-collections/community.postgresql/pull/667#pullrequestreview-1868126048>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AILJV73UFWPBE4Z6E5YT5VDYSONL5AVCNFSM6AAAAABCWZGV2WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNRYGEZDMMBUHA>
> .
> You are receiving this because you were mentioned.Message ID:
> <ansible-collections/community.postgresql/pull/667/review/1868126048@
> github.com>
>

2024-02-08 07:10 UTC, Andersson007 reviewed
@aleszeleny hello, thanks for the contribution! Couple of things from me

2024-02-08 07:10 UTC, Andersson007 commented on plugins/modules/postgresql_db.py
> +    default: ''
```suggestion
    default: ''
    version_added: '3.4.0'
```

2024-02-08 07:10 UTC, Andersson007 commented on plugins/modules/postgresql_db.py
> +    default: ''
```suggestion
    default: ''
    version_added: '3.4.0'
```

2024-02-08 09:38 UTC, aleszeleny commented
> @aleszeleny thanks! also please revert the changes against the changelog and add a fragment as @hunleyd suggested https://github.com/ansible-community/antsibull-changelog/blob/main/docs/changelogs.rst#examples

Just tried to do this in commit d318950

2024-02-08 12:21 UTC, Andersson007 commented on changelogs/fragments/667-db_icu_provider.yml
> +
```suggestion
```

2024-02-08 14:25 UTC, hunleyd approved these changes

2024-02-09 09:54 UTC, Andersson007 approved these changes

2024-02-09 09:55 UTC, merged

2024-02-09 09:55 UTC, Andersson007 commented
@aleszeleny thanks for the contribution! @hunleyd thanks for reviewing and approving!

2024-02-09 11:32 UTC, Andersson007 commented
@aleszeleny 3.4.0 has been released with your features, so you can update your local collection version using `ansible-galaxy` and enjoy it:)

Also you're welcome to join our forum group and the matrix channel, see the [communication guide](https://docs.ansible.com/ansible/devel/community/communication.html) or README for details.