fix(postgresql_ext): Reconnect before upgrade
ansible-collections/community.postgresql pull request #689
Opened 2024-04-26 10:26 UTC by jouir

##### SUMMARY

The TimescaleDB extension needs a fresh connection at upgrade because the extension might be accidentally loaded. The [upgrade procedure](https://docs.timescale.com/self-hosted/latest/upgrades/minor-upgrade/) recommends using the `-X` flag of psql to ignore `.psqlrc` file that might execute some queries and load the extension.

This commit reconnects before performing the extension upgrade to fix the following error:

```
Traceback (most recent call last):
  File "/tmp/ansible_community.postgresql.postgresql_ext_payload_yi1aki7a/ansible_community.postgresql.postgresql_ext_payload.zip/ansible_collections/community/postgresql/plugins/modules/postgresql_ext.py", line 428, in main
  File "/tmp/ansible_community.postgresql.postgresql_ext_payload_yi1aki7a/ansible_community.postgresql.postgresql_ext_payload.zip/ansible_collections/community/postgresql/plugins/modules/postgresql_ext.py", line 246, in ext_update_version
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 146, in execute
    return super().execute(query, vars)
psycopg2.errors.FeatureNotSupported: extension "timescaledb" cannot be updated after the old version has already been loaded
HINT:  Start a new session and execute ALTER EXTENSION as the first command. Make sure to pass the "-X" flag to psql.
```

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
postgresql_ext

2024-04-29 09:10 UTC, Andersson007 commented
@jouir hello, thanks for the pull request! Could you please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) (under `bugfixes:`, i think)

2024-04-29 15:30 UTC, hunleyd requested changes
LGTM, will approve w/ a changelog fragment

2024-05-02 08:12 UTC, Andersson007 commented
@jouir any updates on ^ ?

2024-05-10 11:18 UTC, jouir commented
I've added the changelog fragment as requested.

2024-05-10 12:01 UTC, hunleyd approved these changes

2024-05-10 12:39 UTC, Andersson007 approved these changes

2024-05-13 08:45 UTC, merged

2024-05-13 08:49 UTC, Andersson007 commented
@jouir thanks for the contribution! @hunleyd thanks for reviewing!

@jouir could you please [backport](https://docs.ansible.com/ansible/devel/community/development_process.html#backporting-merged-prs-in-ansible-core) the changes to `stable-2` ? <- the process in the guide is about ansible-core but what you need is to replace `devel` with `main` branch in your mind when applying it.