postgresql_idx: consider schema name when checking
ansible-collections/community.postgresql pull request #693
Opened 2024-05-08 00:55 UTC by rlaager

##### SUMMARY
When checking to see if an index exists, the schema name needs to be taken into account.  That is, the same name can exist in multiple schemas.

Fixes #692

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
community.general.postgresql_idx

2024-05-08 13:29 UTC, hunleyd requested changes
thanks for the fix! could you please add a changelog [fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) under the bugfix: key?

2024-05-08 19:22 UTC, rlaager commented
Done. I'm not sure how verbose you want me to be. I can drop the additional sentences if you prefer shorter.

Also, I wasn't able to find documentation on things like line length, so let me know if I need to rewrap the code (the exec_sql statement) or the changelog fragment.

2024-05-09 12:44 UTC, hunleyd approved these changes

2024-05-10 10:45 UTC, Andersson007 approved these changes

2024-05-10 10:46 UTC, Andersson007 commented
@rlaager hi, welcome to the project and thanks for the contribution!

2024-05-10 10:46 UTC, merged

2024-05-10 10:46 UTC, Andersson007 commented
Merged!
@hunleyd thanks for reviewing!