postgresql_info return values doc section: leave only top level keys info
ansible-collections/community.postgresql pull request #755
Opened 2024-10-18 05:48 UTC by Andersson007

##### SUMMARY
Fixes https://github.com/ansible-collections/community.postgresql/issues/754

##### ISSUE TYPE

- Docs Pull Request

2024-10-18 05:48 UTC, Andersson007 commented
ready for review

2024-10-18 05:59 UTC, Andersson007 commented
ready for review

2024-10-21 12:46 UTC, hunleyd requested changes

2024-10-21 12:46 UTC, hunleyd commented on plugins/modules/postgresql_info.py
> +  - List of settings that are pending until restart to be set.
```suggestion
  - List of changed settings that will take effect upon restart .
```

how's that?

2024-10-22 08:25 UTC, Andersson007 commented
@hunleyd your suggestion LGTM, committed, PTAL

2024-10-23 14:01 UTC, hunleyd approved these changes

2024-10-23 14:01 UTC, merged