fixes and features for the pg_hba module
ansible-collections/community.postgresql pull request #778
Opened 2024-12-04 16:17 UTC by toydarian

##### SUMMARY

 - Adding myself to the CODEOWNERS file for the parts related to `postgresql_pg_hba`
 - Deprecates `keep_comments_at_rules` as discussed in #776 
 - Adds parameter `sort_rules` that allows to disable sorting of rules. The default is `true` to keep to previous behavior
 - Allows a file to contain `include` directives and will keep them at the end of the file. Does not allow to add such directives (#795)
 - Adds the rendered string that is written to the file as an output

Fixes #776 
Fixes #795 

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
`postgresql_pg_hba`

##### ADDITIONAL INFORMATION

- Removes the old `PgHba` class and moves the code to different stand-alone methods
- Adds tests for several edge-cases and new features
- modification in the tests is to account for the changes regarding `keep_comments_at_rules`
- adds required fetch in tests

2024-12-05 07:09 UTC, Andersson007 commented
@toydarian thanks for a lot of good changes! Could you please split the PR into one per changelog entry?

2024-12-05 07:35 UTC, Andersson007 commented
> I can try. It's actually hard, as a lot of the changes are closely tied in together and I want to avoid writing code that will be removed in the next PR.

sure, any smaller PRs would be much appreciated, thanks

2025-01-21 18:15 UTC, hunleyd requested changes
marking as 'changes requested' so my Slack bot stops reminding me about this. once it is out of draft, please re-request me @toydarian . thx!

2025-02-04 14:11 UTC, Andersson007 commented
Just a reminder to change it from draft to ready for review one it's ready, thanks

2025-02-04 14:59 UTC, toydarian commented
@Andersson007 for some reason, when I use the methods from `module`, it fails on SELinux stuff in RHEL in the [CI](https://dev.azure.com/ansible/community.postgresql/_build/results?buildId=136127&view=logs&j=0e7ff078-b0f2-52bd-ae5e-08bbb58fe076&t=88b04eb7-73a8-570e-16db-fd23ef705b06). I don't have one of those at my disposal and the container is also not available for local testing. So I can't really test if it is only in the CI or what is actually going on.  
To make the CI work, I just do all the file-stuff myself, but I would like to do it properly.

So I'm pondering if I should try to get it to work or just make sure the perms are properly set and move the SELinux stuff to a new issue.

2025-02-13 07:45 UTC, Andersson007 commented
@toydarian sorry for the delayed response: the conference. To me it looks like the checks are OK now? Anyway, if there are any issues with a specific distro we can't fix on our side, you could just exclude it using `when:` in the test target

2025-02-24 10:11 UTC, Andersson007 commented
cc @betanummeric @sebasmannem

2025-02-24 10:23 UTC, Andersson007 reviewed
@toydarian epic work, thanks a lot! My eyes feel happy to see the coverage!
From my limited perspective, there are two point:
- Proper parameter deprecation (see the comment), we should also create an issue for milestone 4.0.0 or 5.0.0
- And moving some code out of main to separate functions to improve general module logic understanding (see the comment, but it's up to you, just a suggestion)

2025-02-24 10:23 UTC, Andersson007 commented on plugins/modules/postgresql_pg_hba.py
> +        # DEPRECATED, does nothing
```suggestion
        # DEPRECATED, does nothing
```
should it be deprecated deprecated? please see https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec , there are corresponding fields similar to as we used when deprecating aliases

2025-02-24 10:23 UTC, Andersson007 commented on plugins/modules/postgresql_pg_hba.py
> +    # TODO
```suggestion
    # TODO
```
does it make sense to move these lines to a separate function for readability?

2025-02-24 10:23 UTC, Andersson007 commented on plugins/modules/postgresql_pg_hba.py
> +    new_rules = []
```suggestion
    new_rules = []
```
could we move the below lines to a separate function for logic readability?

2025-02-24 15:56 UTC, toydarian commented on plugins/modules/postgresql_pg_hba.py
> +        # DEPRECATED, does nothing
This actually doesn't do anything anymore. The module behaves as if this is always `true` (which doesn't break anything). So this is only here to ensure the module doesn't throw an error when this is specified. I added the additional fields.

2025-02-24 15:57 UTC, toydarian commented on plugins/modules/postgresql_pg_hba.py
> +    new_rules = []
yes, it does, but I would do this in a later PR

2025-02-24 15:57 UTC, toydarian commented on plugins/modules/postgresql_pg_hba.py
> +    # TODO
yes, it does, but I would do this in a later PR

2025-02-25 08:04 UTC, Andersson007 commented on plugins/modules/postgresql_pg_hba.py
> +        # DEPRECATED, does nothing
@toydarian ok, thanks for explaining, I'll create an issue to properly deprecate it in another PR and remove it as we shouldn't keep any arguments that do nothing

2025-02-25 08:15 UTC, Andersson007 reviewed
@toydarian thanks for the change and comments!
One thing related to the latest changes: could you please add a line under `breaking_changes:` to the fragment announcing that the `keep_comments_at_rules` gonna get removed in 5.0.0?

2025-02-27 14:46 UTC, merged

2025-02-28 09:59 UTC, Andersson007 commented
@toydarian thanks for the contribution!
@hunleyd thanks for reviewing!